#!/usr/bin/env pwsh
[CmdletBinding()]
param([Parameter(Position=0,Mandatory)][ValidateSet('apply','check','inputs','audit','preflight')][string]$Command)
Import-Module (Join-Path $PSScriptRoot 'JFrog.Common.psm1') -Force
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
try { Import-Module powershell-yaml -RequiredVersion 0.4.12 -ErrorAction Stop } catch { Fail 'Install powershell-yaml 0.4.12 with Install-Module powershell-yaml -RequiredVersion 0.4.12 -Scope CurrentUser' }

$etc = '/var/opt/jfrog/artifactory/etc'
$system = "$etc/system.yaml"; $latest = "$etc/access/access.config.latest.yml"; $template = "$etc/access/access.config.template.yml"; $import = "$etc/access/access.config.import.yml"
$access = @{ security = @{ 'allow-anonymous-in-projects' = $false; authentication = @{ 'disable-remember-me' = $true; 'password-autocomplete-enabled' = $false; 'disable-api-key-creation' = $true; 'disable-api-key-authentication' = $true }; 'user-lock-policy' = @{ 'max-login-delay-incorrect-attempts' = 2; 'max-login-delay-millis' = 60000 } } }
$frontend = @{ frontend = @{ featureToggler = @{ accessPlatformAuditor = $true } } }

function ConvertFrom-ServerYaml([string]$Text) { try { $value = $Text | ConvertFrom-Yaml } catch { Fail 'Invalid server YAML; contents suppressed' }; if ($null -eq $value -or $value -isnot [Collections.IDictionary]) { Fail 'Expected a YAML mapping; refusing to replace server configuration' }; $value }
function Copy-Map([Collections.IDictionary]$Value) { (($Value | ConvertTo-Json -Depth 64) | ConvertFrom-Json -AsHashtable -Depth 64) }
function Merge-Map([Collections.IDictionary]$Current, [Collections.IDictionary]$Patch) { $result = Copy-Map $Current; foreach ($key in $Patch.Keys) { $value = $Patch[$key]; if ($value -is [Collections.IDictionary]) { $node = if ($result.Contains($key)) { $result[$key] } else { @{} }; if ($node -isnot [Collections.IDictionary]) { Fail 'Unexpected server configuration structure' }; $result[$key] = Merge-Map $node $value } else { $result[$key] = $value } }; $result }
function Get-Mismatches([Collections.IDictionary]$Current, [Collections.IDictionary]$Expected, [string]$Prefix = '') { $result = [Collections.Generic.List[string]]::new(); foreach ($key in $Expected.Keys) { $path = "$Prefix$key"; $actual = if ($Current -and $Current.Contains($key)) { $Current[$key] } else { $null }; if ($Expected[$key] -is [Collections.IDictionary]) { if ($actual -is [Collections.IDictionary]) { (Get-Mismatches $actual $Expected[$key] "$path.") | ForEach-Object { $result.Add($_) } } else { $result.Add($path) } } elseif ($actual -isnot $Expected[$key].GetType() -or $actual -cne $Expected[$key]) { $result.Add($path) } }; $result }
function Read-Server([string]$Path) { try { return (Invoke-Process -File $Compose[0] -Arguments ($Compose[1..($Compose.Count-1)] + @('exec','-T','artifactory','cat',$Path)) -Capture).Output } catch { Fail "Server configuration unavailable: $Path; obtain the current service-generated configuration before proceeding" } }
function Stage([string]$Path, [string]$Text, [switch]$MustBeAbsent) { $guard = if ($MustBeAbsent) { 'test ! -e "$1" || exit 8;' } else { '' }; $reference = if ($Path -eq $system) { $system } else { $latest }; $command = $guard + ' umask 077; test ! -e "$1.poc-tmp" && cp -p "$2" "$1.poc-tmp" && chmod 600 "$1.poc-tmp" && cat > "$1.poc-tmp" && mv "$1.poc-tmp" "$1"'; Invoke-ProcessWithInput -File $Compose[0] -Arguments ($Compose[1..($Compose.Count-1)] + @('exec','-T','artifactory','sh','-c',$command,'poc',$Path,$reference)) -InputText $Text }
function Get-TemplateDefaults([string]$Text) { $clean = ($Text -split "`r?`n" | Where-Object { ($_.Split('#',2)[0].Trim() -ne 'do-not-import-this-file') }) -join "`n"; ConvertFrom-ServerYaml $clean }
function Check-Deployment { $actual = Merge-Map (Get-TemplateDefaults (Read-Server $template)) (ConvertFrom-ServerYaml (Read-Server $latest)); $failures = Get-Mismatches $actual $access; $failures | ForEach-Object { Write-Output "FAIL/UNKNOWN: $_" }; if ($failures.Count) { Fail 'Access running-configuration read-back incomplete or differs from policy' }; Write-Output 'PASS: Access service-generated settings match; suspension timing still requires live testing.'; if ((Get-Mismatches (ConvertFrom-ServerYaml (Read-Server $system)) $frontend).Count) { Fail 'Platform Auditor deployment flag missing; verify its UI activation after restart' }; Write-Output 'CONFIGURED: Platform Auditor flag; verify role availability in the running UI.' }
function Preflight { [void](Merge-Map (ConvertFrom-ServerYaml (Read-Server $latest)) $access); [void](Merge-Map (ConvertFrom-ServerYaml (Read-Server $system)) $frontend); foreach ($path in @($import,"$system.poc-tmp","$import.poc-tmp")) { Invoke-Process -File $Compose[0] -Arguments ($Compose[1..($Compose.Count-1)] + @('exec','-T','artifactory','test','!','-e',$path)) | Out-Null }; Write-Output 'PASS: deployment source files and pending-file checks.' }
 function Apply-Deployment { & (Join-Path $PSScriptRoot 'Poc.ps1') setup; $token=Get-JFrogToken; if ((Get-JFrogJson '/artifactory/api/system/version' $token).version -ne '7.161.15') { Fail 'Deployment automation is restricted to the pinned 7.161.15 lab' }; Get-JFrogJson $Lock $token | Out-Null; $accessText=Read-Server $latest; $systemText=Read-Server $system; $oldAccess=ConvertFrom-ServerYaml $accessText; $oldSystem=ConvertFrom-ServerYaml $systemText; $newAccess=Merge-Map $oldAccess $access; $newSystem=Merge-Map $oldSystem $frontend; Invoke-Process -File $Compose[0] -Arguments ($Compose[1..($Compose.Count-1)] + @('exec','-T','artifactory','test','!','-e',$import)) | Out-Null; if (($newAccess | ConvertTo-Json -Depth 64 -Compress) -eq ($oldAccess | ConvertTo-Json -Depth 64 -Compress) -and ($newSystem | ConvertTo-Json -Depth 64 -Compress) -eq ($oldSystem | ConvertTo-Json -Depth 64 -Compress)) { Write-Output 'No deployment changes required; verify runtime UI and behaviour separately.'; return }; $backup=Join-Path $Local ('security-backup-'+[guid]::NewGuid().ToString('N')); New-Item -ItemType Directory -Path $backup | Out-Null; if ($IsLinux -or $IsMacOS) { & chmod 700 $backup }; Write-PrivateFile (Join-Path $backup 'access.yml') $accessText; Write-PrivateFile (Join-Path $backup 'system.yaml') $systemText; Stage $import (($newAccess | ConvertTo-Yaml)) -MustBeAbsent; Stage $system (($newSystem | ConvertTo-Yaml)); Invoke-Process -File $Compose[0] -Arguments ($Compose[1..($Compose.Count-1)] + @('restart','artifactory')) | Out-Null; Wait-JFrogReady; Check-Deployment; Write-Output 'Deployment subset applied. Run make verify for outstanding acceptance gates.' }
function Check-Inputs { $path=Join-Path $Local 'security-inputs.json'; if (-not (Test-Path $path)) { Fail 'Copy config/security-inputs.example.json to .local/security-inputs.json; inputs are TBD' }; try { $data=Get-Content -Raw $path | ConvertFrom-Json -AsHashtable } catch { Fail 'Cannot read security inputs; contents suppressed' }; $fields=@('approved_basic_auth_accounts','initial_admin_account','login_dialog_title','login_dialog_text','internal_role_design_reference'); if ($data.Keys.Count -ne $fields.Count -or @($fields | Where-Object { -not $data.Contains($_) }).Count) { Fail 'Security input keys must match the example exactly' }; $accounts=@($data.approved_basic_auth_accounts); if (-not $accounts.Count -or @($accounts | Where-Object { $_ -isnot [string] -or -not $_.Trim() -or $_.Trim() -ne $_ -or $_ -match '[<>]' }).Count -or (@($accounts | ForEach-Object { $_.ToLowerInvariant() } | Select-Object -Unique).Count -ne $accounts.Count)) { Fail 'Approved Basic-auth identities are required and unique; no placeholders' }; foreach ($field in @($fields | Where-Object { $_ -ne 'approved_basic_auth_accounts' })) { if ($data[$field] -isnot [string] -or -not $data[$field].Trim() -or $data[$field].Trim().ToUpperInvariant() -eq 'TBD') { Fail "$field is required and still TBD" } }; Write-Output 'Inputs complete; this does not apply or approve them. Follow docs/coverage.md.' }
function Audit-Assignments { $token=Get-JFrogToken; Get-JFrogJson $Lock $token | Out-Null; $findings=[Collections.Generic.List[string]]::new(); $group=Invoke-JFrogApi -Method GET -Path '/artifactory/api/security/groups/readers?includeUsers=true' -Token $token -Allowed @(200,404); if ($group.StatusCode -eq 200) { $value=$group.Content | ConvertFrom-Json -AsHashtable; if ($value.userNames -isnot [array]) { Fail 'Cannot establish readers membership; deletion prohibited' }; $findings.Add("readers group exists; members=$($value.userNames.Count)"); if ($value.autoJoin -ne $false) { $findings.Add('readers autoJoin enabled or unknown') } }; $permissions=Get-JFrogJson '/artifactory/api/v2/security/permissions' $token; if ($permissions -isnot [array]) { Fail 'Unknown permission-list schema; dependency audit incomplete' }; foreach ($item in $permissions) { $permission=Get-JFrogJson ('/artifactory/api/v2/security/permissions/'+[uri]::EscapeDataString($item.name)) $token; foreach ($scope in @('repo','build','releaseBundle')) { if ($permission.Contains($scope)) { foreach ($kind in @('groups','users')) { $principal=$permission[$scope].actions[$kind]; $name=if($kind -eq 'groups'){'readers'}else{'anonymous'}; if ($principal -is [Collections.IDictionary] -and $principal.Contains($name)) { $findings.Add("$scope`: forbidden $name permission assignment") } } } } }; $findings | ForEach-Object { Write-Output "FAIL: $_" }; Write-Output 'MANUAL: inspect project roles/members, IdP mappings and token scopes before readers removal.'; if ($findings.Count) { Fail 'Forbidden principal/group dependencies found; no objects were modified' }; Write-Output 'PASS: legacy permission/group subset only; project/IdP audit is still required.' }
try { switch ($Command) { 'apply' { Apply-Deployment }; 'check' { Check-Deployment }; 'preflight' { Preflight }; 'inputs' { Check-Inputs }; 'audit' { Audit-Assignments } } } catch { Write-Error "ERROR: $($_.Exception.Message)"; exit 1 }
